// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  homepage_header: dynamic(() => import('./HomepageHeader')),
  homepage_join_our_club: dynamic(() => import('./HomepageJoinOurClub')),
  homepage_lets_connect: dynamic(() => import('./HomepageLetsConnect')),
  homepage_our_stars: dynamic(() => import('./HomepageOurStars')),
  homepage_probiotics: dynamic(() => import('./HomepageProbiotics')),
};
